/**
 * Lista estática de emojis do `EmojiPicker` (CRMLAB-73, D-243).
 *
 * Versionada no repo, sem dependência: ~550 emojis em 8 categorias na ordem do
 * WhatsApp, cada um com NOME em pt-BR (o `aria-label` do botão) e palavras-chave
 * para a busca. Emoji novo entra aqui; nome é o que a recepção digitaria.
 *
 * Formato compacto: `[caractere, nome, palavras-chave separadas por espaço]`.
 */

export type EmojiCategoryId =
  | 'smileys'
  | 'animals'
  | 'food'
  | 'activities'
  | 'travel'
  | 'objects'
  | 'symbols'
  | 'flags';

export interface Emoji {
  char: string;
  label: string;
  keywords: string;
}

export interface EmojiCategory {
  id: EmojiCategoryId;
  label: string;
  /** Emoji que representa a aba. */
  icon: string;
  emojis: readonly Emoji[];
}

type Row = readonly [char: string, label: string, keywords?: string];

const SMILEYS: readonly Row[] = [
  ['😀', 'sorriso', 'feliz alegre'],
  ['😃', 'sorriso aberto', 'feliz alegre'],
  ['😄', 'sorriso com olhos felizes', 'feliz alegre risada'],
  ['😁', 'sorriso animado', 'feliz dentes'],
  ['😆', 'rindo', 'risada gargalhada'],
  ['😅', 'sorriso sem graça', 'suor alivio nervoso'],
  ['😂', 'chorando de rir', 'risada kkk lagrimas'],
  ['🤣', 'rolando de rir', 'risada kkk gargalhada'],
  ['🥲', 'sorriso com lágrima', 'emocionado'],
  ['😊', 'sorriso tímido', 'feliz corado fofo'],
  ['😇', 'anjinho', 'inocente anjo'],
  ['🙂', 'sorriso leve', 'ok feliz'],
  ['🙃', 'de cabeça para baixo', 'ironia'],
  ['😉', 'piscadinha', 'piscar'],
  ['😌', 'aliviado', 'calma paz'],
  ['😍', 'olhos de coração', 'amor apaixonado'],
  ['🥰', 'apaixonado', 'amor coracoes carinho'],
  ['😘', 'mandando beijo', 'beijo amor'],
  ['😗', 'beijo', 'beijinho'],
  ['😚', 'beijo tímido', 'beijinho'],
  ['😋', 'delícia', 'gostoso comida lingua'],
  ['😛', 'língua de fora', 'brincadeira'],
  ['😜', 'piscando com língua', 'brincadeira zoeira'],
  ['🤪', 'maluquinho', 'doido zoeira'],
  ['😝', 'língua e olhos fechados', 'brincadeira'],
  ['🤑', 'cara de dinheiro', 'rico grana'],
  ['🤗', 'abraço', 'abraco carinho'],
  ['🤭', 'mão na boca', 'ops risadinha'],
  ['🤫', 'silêncio', 'segredo psiu'],
  ['🤔', 'pensando', 'duvida hmm'],
  ['🤐', 'boca fechada', 'segredo ziper'],
  ['🤨', 'desconfiado', 'sobrancelha duvida'],
  ['😐', 'sem expressão', 'neutro serio'],
  ['😑', 'inexpressivo', 'neutro tedio'],
  ['😶', 'sem boca', 'mudo calado'],
  ['😏', 'sorriso de lado', 'malicioso'],
  ['😒', 'entediado', 'insatisfeito'],
  ['🙄', 'revirando os olhos', 'tedio aff'],
  ['😬', 'careta', 'tenso nervoso'],
  ['🤥', 'mentiroso', 'mentira pinoquio'],
  ['😔', 'pensativo', 'triste desanimado'],
  ['😪', 'sonolento', 'sono'],
  ['🤤', 'babando', 'fome vontade'],
  ['😴', 'dormindo', 'sono zzz'],
  ['😷', 'máscara', 'doente mascara saude'],
  ['🤒', 'doente', 'febre termometro'],
  ['🤕', 'machucado', 'curativo ferido'],
  ['🤢', 'enjoado', 'nausea'],
  ['🤮', 'vomitando', 'vomito enjoo'],
  ['🤧', 'espirrando', 'gripe resfriado'],
  ['🥵', 'com calor', 'quente suor'],
  ['🥶', 'com frio', 'gelado congelando'],
  ['🥴', 'tonto', 'zonzo'],
  ['😵', 'atordoado', 'tonto'],
  ['🤯', 'cabeça explodindo', 'chocado'],
  ['🥳', 'festejando', 'festa aniversario comemoracao'],
  ['😎', 'óculos escuros', 'estiloso legal'],
  ['🤓', 'nerd', 'estudioso oculos'],
  ['🧐', 'monóculo', 'analisando'],
  ['😕', 'confuso', 'duvida'],
  ['😟', 'preocupado', 'aflito'],
  ['🙁', 'um pouco triste', 'triste'],
  ['😮', 'boca aberta', 'surpreso uau'],
  ['😯', 'espantado', 'surpreso'],
  ['😲', 'impressionado', 'surpreso chocado'],
  ['😳', 'surpreso', 'envergonhado corado'],
  ['🥺', 'olhinhos pidões', 'por favor suplicando'],
  ['😦', 'assustado', 'susto'],
  ['😨', 'com medo', 'medo'],
  ['😰', 'ansioso', 'suor preocupado'],
  ['😥', 'decepcionado', 'triste alivio'],
  ['😢', 'triste', 'lagrima choro'],
  ['😭', 'chorando', 'choro lagrimas'],
  ['😱', 'gritando de medo', 'pavor susto'],
  ['😖', 'frustrado', 'confuso'],
  ['😣', 'perseverante', 'esforco'],
  ['😞', 'desapontado', 'triste'],
  ['😓', 'suando frio', 'cansado'],
  ['😩', 'exausto', 'cansado'],
  ['😫', 'cansado', 'exausto'],
  ['🥱', 'bocejando', 'sono tedio'],
  ['😤', 'bufando', 'raiva triunfo'],
  ['😡', 'furioso', 'raiva bravo'],
  ['😠', 'bravo', 'raiva irritado'],
  ['🤬', 'xingando', 'palavrao raiva'],
  ['😈', 'diabinho', 'travesso'],
  ['💀', 'caveira', 'morri'],
  ['💩', 'cocô', 'coco'],
  ['🤡', 'palhaço', 'palhaco'],
  ['👻', 'fantasma', 'susto'],
  ['🤖', 'robô', 'robo automatico'],
  ['😺', 'gato sorrindo', 'gatinho'],
  ['🙈', 'macaco não vejo', 'vergonha'],
  ['🙉', 'macaco não ouço', 'surdo'],
  ['🙊', 'macaco não falo', 'segredo'],
  ['👋', 'aceno', 'oi tchau ola'],
  ['🤚', 'mão levantada', 'pare'],
  ['✋', 'mão aberta', 'pare espera'],
  ['🖖', 'saudação vulcana', 'spock'],
  ['👌', 'ok', 'perfeito beleza'],
  ['🤌', 'dedos juntos', 'italiano'],
  ['🤏', 'pouquinho', 'pequeno'],
  ['✌️', 'paz e amor', 'vitoria dois'],
  ['🤞', 'dedos cruzados', 'sorte torcendo'],
  ['🤟', 'te amo', 'amor libras'],
  ['🤘', 'rock', 'chifre'],
  ['🤙', 'me liga', 'telefone hang loose'],
  ['👈', 'apontando para a esquerda', 'esquerda'],
  ['👉', 'apontando para a direita', 'direita'],
  ['👆', 'apontando para cima', 'cima'],
  ['👇', 'apontando para baixo', 'baixo'],
  ['☝️', 'indicador para cima', 'atencao um'],
  ['👍', 'joinha', 'positivo ok curti legal'],
  ['👎', 'não curti', 'negativo'],
  ['✊', 'punho', 'forca'],
  ['👊', 'soquinho', 'punho toca aqui'],
  ['👏', 'palmas', 'aplausos parabens'],
  ['🙌', 'comemorando', 'aleluia maos'],
  ['👐', 'mãos abertas', 'abraco'],
  ['🤲', 'palmas para cima', 'oracao pedido'],
  ['🤝', 'aperto de mãos', 'acordo combinado negocio'],
  ['🙏', 'obrigado', 'por favor oracao gratidao amem'],
  ['✍️', 'escrevendo', 'assinatura'],
  ['💅', 'unhas', 'esmalte'],
  ['💪', 'força', 'forca musculo'],
  ['👀', 'olhos', 'olhando vendo'],
  ['👁️', 'olho', 'visao'],
  ['👂', 'orelha', 'ouvido audicao'],
  ['👃', 'nariz', 'olfato'],
  ['🧠', 'cérebro', 'cerebro mente'],
  ['🫀', 'coração anatômico', 'cardiaco cardiologia'],
  ['🫁', 'pulmões', 'pulmao respiracao'],
  ['🦷', 'dente', 'dentista odontologia'],
  ['🦴', 'osso', 'ortopedia'],
  ['👶', 'bebê', 'bebe crianca recem nascido'],
  ['🧒', 'criança', 'crianca'],
  ['👦', 'menino', 'crianca'],
  ['👧', 'menina', 'crianca'],
  ['🧑', 'pessoa', 'adulto'],
  ['👨', 'homem', 'adulto'],
  ['👩', 'mulher', 'adulta'],
  ['🧓', 'pessoa idosa', 'idoso'],
  ['👴', 'idoso', 'avo vovo'],
  ['👵', 'idosa', 'avo vovo'],
  ['🧑‍⚕️', 'profissional de saúde', 'medico enfermeiro saude'],
  ['👨‍⚕️', 'médico', 'medico doutor saude'],
  ['👩‍⚕️', 'médica', 'medica doutora saude enfermeira'],
  ['🧑‍🔬', 'cientista', 'laboratorio pesquisa biomedico'],
  ['🤰', 'grávida', 'gravida gestante gestacao'],
  ['🤱', 'amamentando', 'mae bebe'],
  ['👪', 'família', 'familia'],
  ['🧍', 'pessoa em pé', 'fila'],
  ['🚶', 'pessoa andando', 'caminhando'],
  ['🏃', 'pessoa correndo', 'corrida pressa'],
  ['🧑‍🦽', 'cadeira de rodas', 'acessibilidade'],
  ['🗣️', 'falando', 'fala voz'],
  ['👤', 'silhueta', 'perfil usuario'],
];

const ANIMALS: readonly Row[] = [
  ['🐶', 'cachorro', 'cao cachorrinho'],
  ['🐱', 'gato', 'gatinho'],
  ['🐭', 'rato', 'camundongo'],
  ['🐰', 'coelho', 'pascoa'],
  ['🦊', 'raposa'],
  ['🐻', 'urso'],
  ['🐼', 'panda'],
  ['🐨', 'coala'],
  ['🐯', 'tigre'],
  ['🦁', 'leão', 'leao'],
  ['🐮', 'vaca'],
  ['🐷', 'porco', 'porquinho'],
  ['🐸', 'sapo'],
  ['🐵', 'macaco'],
  ['🐔', 'galinha'],
  ['🐧', 'pinguim'],
  ['🐦', 'pássaro', 'passaro'],
  ['🐤', 'pintinho'],
  ['🦆', 'pato'],
  ['🦉', 'coruja'],
  ['🐴', 'cavalo'],
  ['🦄', 'unicórnio', 'unicornio'],
  ['🐝', 'abelha'],
  ['🐛', 'lagarta'],
  ['🦋', 'borboleta'],
  ['🐌', 'caracol', 'lento devagar'],
  ['🐞', 'joaninha'],
  ['🐜', 'formiga'],
  ['🦟', 'mosquito', 'dengue'],
  ['🐢', 'tartaruga', 'lento devagar'],
  ['🐍', 'cobra'],
  ['🐙', 'polvo'],
  ['🐠', 'peixe tropical', 'peixe'],
  ['🐟', 'peixe'],
  ['🐬', 'golfinho'],
  ['🐳', 'baleia'],
  ['🦈', 'tubarão', 'tubarao'],
  ['🐊', 'jacaré', 'jacare'],
  ['🦒', 'girafa'],
  ['🐘', 'elefante'],
  ['🦠', 'micróbio', 'microbio virus bacteria'],
  ['🐾', 'pegadas', 'patinhas'],
  ['💐', 'buquê', 'buque flores'],
  ['🌸', 'flor de cerejeira', 'flor'],
  ['🌹', 'rosa', 'flor'],
  ['🌺', 'hibisco', 'flor'],
  ['🌻', 'girassol', 'flor'],
  ['🌼', 'florzinha', 'flor'],
  ['🌷', 'tulipa', 'flor'],
  ['🌱', 'broto', 'planta'],
  ['🌿', 'erva', 'folha planta'],
  ['🍀', 'trevo de quatro folhas', 'sorte'],
  ['🍁', 'folha de bordo', 'outono'],
  ['🌳', 'árvore', 'arvore'],
  ['🌴', 'palmeira', 'praia'],
  ['🌵', 'cacto'],
  ['🌞', 'sol com rosto', 'sol'],
  ['☀️', 'sol', 'calor dia'],
  ['🌤️', 'sol com nuvem', 'tempo'],
  ['⛅', 'parcialmente nublado', 'tempo nuvem'],
  ['☁️', 'nuvem', 'nublado'],
  ['🌧️', 'chuva', 'chovendo'],
  ['⛈️', 'tempestade', 'trovao chuva'],
  ['❄️', 'floco de neve', 'frio neve'],
  ['🌈', 'arco-íris', 'arco iris'],
  ['🌙', 'lua', 'noite'],
  ['⭐', 'estrela'],
  ['🌟', 'estrela brilhante', 'brilho'],
  ['✨', 'brilho', 'brilhos magia'],
  ['⚡', 'raio', 'energia rapido'],
  ['🔥', 'fogo', 'quente'],
  ['💧', 'gota', 'agua'],
  ['🌊', 'onda', 'mar'],
];

const FOOD: readonly Row[] = [
  ['🍏', 'maçã verde', 'maca fruta'],
  ['🍎', 'maçã', 'maca fruta'],
  ['🍐', 'pera', 'fruta'],
  ['🍊', 'laranja', 'fruta'],
  ['🍋', 'limão', 'limao fruta'],
  ['🍌', 'banana', 'fruta'],
  ['🍉', 'melancia', 'fruta'],
  ['🍇', 'uva', 'fruta'],
  ['🍓', 'morango', 'fruta'],
  ['🍒', 'cereja', 'fruta'],
  ['🍑', 'pêssego', 'pessego fruta'],
  ['🥭', 'manga', 'fruta'],
  ['🍍', 'abacaxi', 'fruta'],
  ['🥥', 'coco', 'fruta'],
  ['🥝', 'kiwi', 'fruta'],
  ['🍅', 'tomate'],
  ['🥑', 'abacate'],
  ['🥦', 'brócolis', 'brocolis verdura'],
  ['🥬', 'folhas verdes', 'alface verdura'],
  ['🥒', 'pepino'],
  ['🌶️', 'pimenta'],
  ['🌽', 'milho'],
  ['🥕', 'cenoura'],
  ['🧄', 'alho'],
  ['🧅', 'cebola'],
  ['🥔', 'batata'],
  ['🍞', 'pão', 'pao'],
  ['🥐', 'croissant', 'pao'],
  ['🧀', 'queijo'],
  ['🥚', 'ovo'],
  ['🍳', 'ovo frito', 'cafe da manha'],
  ['🥓', 'bacon'],
  ['🥩', 'carne'],
  ['🍗', 'coxa de frango', 'frango'],
  ['🍔', 'hambúrguer', 'hamburguer lanche'],
  ['🍟', 'batata frita'],
  ['🍕', 'pizza'],
  ['🌭', 'cachorro-quente', 'cachorro quente'],
  ['🥪', 'sanduíche', 'sanduiche lanche'],
  ['🌮', 'taco'],
  ['🥗', 'salada', 'dieta'],
  ['🍝', 'macarrão', 'macarrao'],
  ['🍜', 'lámen', 'sopa'],
  ['🍲', 'panela de comida', 'sopa'],
  ['🍣', 'sushi'],
  ['🍚', 'arroz'],
  ['🍰', 'fatia de bolo', 'bolo doce'],
  ['🎂', 'bolo de aniversário', 'aniversario bolo'],
  ['🧁', 'cupcake', 'bolinho'],
  ['🍫', 'chocolate', 'doce'],
  ['🍬', 'bala', 'doce'],
  ['🍭', 'pirulito', 'doce'],
  ['🍩', 'rosquinha', 'donut'],
  ['🍪', 'biscoito', 'bolacha'],
  ['🍯', 'mel'],
  ['🍦', 'sorvete'],
  ['🥛', 'copo de leite', 'leite'],
  ['☕', 'café', 'cafe'],
  ['🍵', 'chá', 'cha'],
  ['🧃', 'suco de caixinha', 'suco'],
  ['🥤', 'copo com canudo', 'refrigerante suco'],
  ['🍺', 'cerveja'],
  ['🍷', 'vinho'],
  ['🥂', 'brinde', 'comemoracao'],
  ['🍽️', 'prato e talheres', 'jejum refeicao almoco'],
  ['🚰', 'água potável', 'agua'],
];

const ACTIVITIES: readonly Row[] = [
  ['⚽', 'bola de futebol', 'futebol'],
  ['🏀', 'basquete'],
  ['🏐', 'vôlei', 'volei'],
  ['🎾', 'tênis', 'tenis'],
  ['🏓', 'pingue-pongue', 'ping pong'],
  ['🥊', 'luva de boxe', 'boxe'],
  ['🏋️', 'levantando peso', 'academia musculacao'],
  ['🧘', 'ioga', 'yoga meditacao'],
  ['🚴', 'ciclista', 'bicicleta'],
  ['🏊', 'natação', 'natacao'],
  ['🏆', 'troféu', 'trofeu campeao'],
  ['🥇', 'medalha de ouro', 'primeiro lugar'],
  ['🏅', 'medalha'],
  ['🎉', 'festa', 'parabens comemoracao confete'],
  ['🎊', 'confete', 'festa'],
  ['🎈', 'balão', 'balao festa'],
  ['🎁', 'presente', 'aniversario'],
  ['🎀', 'laço', 'laco'],
  ['🎄', 'árvore de natal', 'natal'],
  ['🎃', 'abóbora', 'halloween'],
  ['🎆', 'fogos de artifício', 'ano novo'],
  ['🎨', 'paleta de pintura', 'arte'],
  ['🎬', 'claquete', 'filme'],
  ['🎤', 'microfone', 'cantar'],
  ['🎧', 'fone de ouvido', 'musica'],
  ['🎵', 'nota musical', 'musica'],
  ['🎶', 'notas musicais', 'musica'],
  ['🎸', 'guitarra'],
  ['🎮', 'videogame', 'jogo'],
  ['🎲', 'dado', 'jogo sorte'],
  ['🧩', 'quebra-cabeça', 'quebra cabeca'],
  ['🎯', 'alvo', 'meta objetivo'],
];

const TRAVEL: readonly Row[] = [
  ['🚗', 'carro'],
  ['🚕', 'táxi', 'taxi'],
  ['🚌', 'ônibus', 'onibus'],
  ['🚑', 'ambulância', 'ambulancia emergencia'],
  ['🚒', 'caminhão de bombeiros', 'bombeiro'],
  ['🚓', 'viatura de polícia', 'policia'],
  ['🏍️', 'moto', 'motocicleta motoboy'],
  ['🚲', 'bicicleta'],
  ['🛵', 'motoneta', 'entrega'],
  ['✈️', 'avião', 'aviao viagem'],
  ['🚀', 'foguete', 'rapido'],
  ['🚆', 'trem'],
  ['⛽', 'posto de gasolina', 'combustivel'],
  ['🚦', 'semáforo', 'semaforo'],
  ['🅿️', 'estacionamento', 'parking vaga'],
  ['🗺️', 'mapa', 'localizacao'],
  ['📍', 'endereço', 'localizacao local pino mapa'],
  ['🏠', 'casa', 'lar residencia'],
  ['🏡', 'casa com jardim', 'casa'],
  ['🏢', 'prédio', 'predio escritorio'],
  ['🏥', 'hospital', 'saude clinica'],
  ['🏦', 'banco'],
  ['🏪', 'loja de conveniência', 'loja'],
  ['🏫', 'escola'],
  ['⛪', 'igreja'],
  ['🏖️', 'praia', 'ferias'],
  ['⛰️', 'montanha'],
  ['🌆', 'cidade ao entardecer', 'cidade'],
  ['🌃', 'noite estrelada', 'noite'],
  ['🧭', 'bússola', 'bussola direcao'],
  ['⏰', 'horário', 'despertador relogio hora horario'],
  ['⌚', 'relógio de pulso', 'relogio hora'],
  ['⏳', 'ampulheta', 'aguarde espera tempo'],
  ['⌛', 'ampulheta cheia', 'tempo esgotado'],
  ['🕐', 'uma hora', 'relogio hora'],
];

const OBJECTS: readonly Row[] = [
  ['📱', 'celular', 'telefone smartphone whatsapp'],
  ['📞', 'telefone', 'ligar ligacao contato'],
  ['☎️', 'telefone fixo', 'ligar'],
  ['💻', 'notebook', 'computador'],
  ['🖥️', 'computador', 'monitor'],
  ['🖨️', 'impressora', 'imprimir'],
  ['📷', 'câmera', 'camera foto'],
  ['📸', 'câmera com flash', 'foto'],
  ['📺', 'televisão', 'televisao tv'],
  ['🔋', 'bateria'],
  ['🔌', 'tomada'],
  ['💡', 'lâmpada', 'lampada ideia'],
  ['🔦', 'lanterna'],
  ['💸', 'dinheiro voando', 'gasto pagamento'],
  ['💵', 'nota de dólar', 'dinheiro'],
  ['💰', 'dinheiro', 'saco de dinheiro valor preco'],
  ['💳', 'pagamento', 'cartao credito debito'],
  ['🧾', 'recibo', 'nota fiscal comprovante'],
  ['💎', 'diamante', 'joia'],
  ['🔧', 'chave inglesa', 'ferramenta conserto'],
  ['🔨', 'martelo', 'ferramenta'],
  ['⚙️', 'engrenagem', 'configuracao'],
  ['🔬', 'microscópio', 'microscopio laboratorio analise'],
  ['🔭', 'telescópio', 'telescopio'],
  ['🧪', 'exame', 'tubo de ensaio laboratorio amostra'],
  ['🧫', 'placa de petri', 'cultura laboratorio'],
  ['🧬', 'DNA', 'genetica dna'],
  ['🩸', 'gota de sangue', 'sangue coleta'],
  ['💉', 'seringa', 'injecao vacina coleta'],
  ['💊', 'remédio', 'remedio comprimido pilula'],
  ['🩹', 'curativo', 'band-aid'],
  ['🩺', 'estetoscópio', 'estetoscopio medico consulta'],
  ['🩻', 'raio-x', 'raio x radiografia'],
  ['🌡️', 'termômetro', 'termometro febre temperatura'],
  ['🦽', 'cadeira de rodas manual', 'acessibilidade'],
  ['🩼', 'muleta'],
  ['🧴', 'frasco', 'pote amostra'],
  ['🧼', 'sabonete', 'higiene'],
  ['🧻', 'papel higiênico', 'papel'],
  ['🪥', 'escova de dente', 'higiene'],
  ['🚽', 'vaso sanitário', 'banheiro'],
  ['🛏️', 'cama', 'dormir'],
  ['🚪', 'porta', 'entrada'],
  ['🔑', 'chave'],
  ['🔒', 'cadeado fechado', 'seguro senha'],
  ['🔓', 'cadeado aberto', 'desbloqueado'],
  ['🛒', 'carrinho de compras', 'compras'],
  ['🛍️', 'sacolas de compras', 'compras'],
  ['📦', 'caixa', 'pacote entrega'],
  ['✉️', 'envelope', 'carta email'],
  ['📧', 'e-mail', 'email'],
  ['📩', 'envelope com seta', 'recebido'],
  ['📬', 'caixa de correio', 'correio'],
  ['📝', 'anotação', 'anotacao nota escrever formulario'],
  ['📄', 'documento', 'papel pagina resultado laudo'],
  ['📃', 'página', 'pagina documento'],
  ['📑', 'marcadores', 'documentos'],
  ['📋', 'prancheta', 'lista checklist pedido medico'],
  ['📁', 'pasta', 'arquivo'],
  ['📂', 'pasta aberta', 'arquivo'],
  ['📅', 'calendário', 'calendario data agenda agendamento'],
  ['📆', 'calendário de folhas', 'calendario data'],
  ['🗓️', 'agenda', 'calendario data'],
  ['📊', 'gráfico de barras', 'grafico'],
  ['📈', 'gráfico subindo', 'grafico aumento'],
  ['📉', 'gráfico descendo', 'grafico queda'],
  ['📌', 'tachinha', 'fixar'],
  ['📎', 'clipe', 'anexo'],
  ['✂️', 'tesoura', 'cortar'],
  ['🖊️', 'caneta'],
  ['✏️', 'lápis', 'lapis escrever'],
  ['🔍', 'lupa', 'buscar procurar'],
  ['📚', 'livros', 'estudo'],
  ['📖', 'livro aberto', 'leitura'],
  ['🔔', 'sino', 'notificacao aviso'],
  ['🔕', 'sino cortado', 'silencioso'],
  ['📢', 'megafone', 'aviso anuncio'],
  ['📣', 'alto-falante', 'aviso'],
  ['⏱️', 'cronômetro', 'cronometro tempo'],
  ['🗑️', 'lixeira', 'lixo apagar'],
];

const SYMBOLS: readonly Row[] = [
  ['❤️', 'coração', 'coracao amor vermelho'],
  ['🧡', 'coração laranja', 'coracao'],
  ['💛', 'coração amarelo', 'coracao'],
  ['💚', 'coração verde', 'coracao'],
  ['💙', 'coração azul', 'coracao'],
  ['💜', 'coração roxo', 'coracao'],
  ['🖤', 'coração preto', 'coracao'],
  ['🤍', 'coração branco', 'coracao'],
  ['🤎', 'coração marrom', 'coracao'],
  ['💔', 'coração partido', 'coracao triste'],
  ['❣️', 'coração exclamação', 'coracao'],
  ['💕', 'dois corações', 'coracoes amor'],
  ['💖', 'coração brilhante', 'coracao'],
  ['💗', 'coração crescendo', 'coracao'],
  ['💘', 'coração com flecha', 'coracao cupido'],
  ['💝', 'coração com laço', 'coracao presente'],
  ['💯', 'cem pontos', 'cem perfeito'],
  ['💢', 'raiva', 'bravo'],
  ['💬', 'balão de fala', 'mensagem conversa chat'],
  ['💭', 'balão de pensamento', 'pensando'],
  ['💤', 'zzz', 'sono dormindo'],
  ['✅', 'confirmado', 'certo ok feito check'],
  ['☑️', 'caixa marcada', 'check'],
  ['✔️', 'visto', 'certo check'],
  ['❌', 'erro', 'x errado cancelado nao'],
  ['❎', 'x em quadrado', 'cancelado'],
  ['➕', 'mais', 'adicionar soma'],
  ['➖', 'menos', 'subtrair'],
  ['➗', 'dividir', 'divisao'],
  ['✖️', 'multiplicar', 'vezes'],
  ['❓', 'interrogação', 'interrogacao pergunta duvida'],
  ['❔', 'interrogação branca', 'pergunta'],
  ['❗', 'exclamação', 'exclamacao importante'],
  ['❕', 'exclamação branca', 'exclamacao'],
  ['‼️', 'dupla exclamação', 'exclamacao'],
  ['⁉️', 'exclamação e interrogação', 'surpresa'],
  ['⚠️', 'atenção', 'atencao cuidado aviso alerta'],
  ['🚫', 'proibido', 'nao permitido'],
  ['⛔', 'entrada proibida', 'pare'],
  ['🛑', 'placa de pare', 'pare stop'],
  ['🔴', 'círculo vermelho', 'circulo vermelho'],
  ['🟠', 'círculo laranja', 'circulo'],
  ['🟡', 'círculo amarelo', 'circulo'],
  ['🟢', 'círculo verde', 'circulo'],
  ['🔵', 'círculo azul', 'circulo'],
  ['🟣', 'círculo roxo', 'circulo'],
  ['⚫', 'círculo preto', 'circulo'],
  ['⚪', 'círculo branco', 'circulo'],
  ['🔺', 'triângulo vermelho', 'triangulo'],
  ['🔻', 'triângulo para baixo', 'triangulo'],
  ['🔸', 'losango laranja', 'losango'],
  ['🔹', 'losango azul', 'losango'],
  ['▶️', 'play', 'tocar'],
  ['⏸️', 'pausa', 'pausar'],
  ['⏹️', 'parar', 'stop'],
  ['🔁', 'repetir', 'repeticao'],
  ['🔄', 'atualizar', 'recarregar setas'],
  ['⬆️', 'seta para cima', 'cima'],
  ['⬇️', 'seta para baixo', 'baixo'],
  ['⬅️', 'seta para a esquerda', 'esquerda voltar'],
  ['➡️', 'seta para a direita', 'direita'],
  ['↩️', 'seta de retorno', 'voltar'],
  ['🔝', 'topo', 'top'],
  ['🆗', 'botão ok', 'ok'],
  ['🆕', 'novo', 'new'],
  ['🆓', 'grátis', 'gratis free'],
  ['🆘', 'socorro', 'sos ajuda emergencia'],
  ['ℹ️', 'informação', 'informacao info'],
  ['🔞', 'proibido para menores', 'mais de 18'],
  ['♻️', 'reciclagem', 'reciclar'],
  ['⚕️', 'símbolo da medicina', 'medicina saude'],
  ['♀️', 'feminino', 'mulher'],
  ['♂️', 'masculino', 'homem'],
  ['©️', 'copyright', 'direitos'],
  ['®️', 'marca registrada', 'registrado'],
  ['™️', 'marca', 'trademark'],
  ['#️⃣', 'cerquilha', 'hashtag jogo da velha'],
  ['*️⃣', 'asterisco', 'estrela'],
  ['0️⃣', 'zero', 'numero 0'],
  ['1️⃣', 'um', 'numero 1'],
  ['2️⃣', 'dois', 'numero 2'],
  ['3️⃣', 'três', 'tres numero 3'],
  ['4️⃣', 'quatro', 'numero 4'],
  ['5️⃣', 'cinco', 'numero 5'],
  ['6️⃣', 'seis', 'numero 6'],
  ['7️⃣', 'sete', 'numero 7'],
  ['8️⃣', 'oito', 'numero 8'],
  ['9️⃣', 'nove', 'numero 9'],
  ['🔟', 'dez', 'numero 10'],
];

const FLAGS: readonly Row[] = [
  ['🇧🇷', 'bandeira do Brasil', 'brasil'],
  ['🇵🇹', 'bandeira de Portugal', 'portugal'],
  ['🇦🇷', 'bandeira da Argentina', 'argentina'],
  ['🇺🇾', 'bandeira do Uruguai', 'uruguai'],
  ['🇵🇾', 'bandeira do Paraguai', 'paraguai'],
  ['🇨🇱', 'bandeira do Chile', 'chile'],
  ['🇺🇸', 'bandeira dos Estados Unidos', 'eua estados unidos'],
  ['🇪🇸', 'bandeira da Espanha', 'espanha'],
  ['🇮🇹', 'bandeira da Itália', 'italia'],
  ['🇩🇪', 'bandeira da Alemanha', 'alemanha'],
  ['🇫🇷', 'bandeira da França', 'franca'],
  ['🇯🇵', 'bandeira do Japão', 'japao'],
  ['🏳️', 'bandeira branca', 'paz'],
  ['🏴', 'bandeira preta'],
  ['🏁', 'bandeira quadriculada', 'chegada corrida'],
  ['🚩', 'bandeira vermelha', 'alerta'],
  ['🏳️‍🌈', 'bandeira do arco-íris', 'orgulho lgbt'],
];

function toEmojis(rows: readonly Row[]): Emoji[] {
  return rows.map(([char, label, keywords = '']) => ({ char, label, keywords }));
}

export const EMOJI_CATEGORIES: readonly EmojiCategory[] = [
  { id: 'smileys', label: 'Smileys e pessoas', icon: '😀', emojis: toEmojis(SMILEYS) },
  { id: 'animals', label: 'Animais e natureza', icon: '🐶', emojis: toEmojis(ANIMALS) },
  { id: 'food', label: 'Comidas e bebidas', icon: '🍎', emojis: toEmojis(FOOD) },
  { id: 'activities', label: 'Atividades', icon: '⚽', emojis: toEmojis(ACTIVITIES) },
  { id: 'travel', label: 'Viagens e lugares', icon: '🚗', emojis: toEmojis(TRAVEL) },
  { id: 'objects', label: 'Objetos', icon: '💡', emojis: toEmojis(OBJECTS) },
  { id: 'symbols', label: 'Símbolos', icon: '❤️', emojis: toEmojis(SYMBOLS) },
  { id: 'flags', label: 'Bandeiras', icon: '🏳️', emojis: toEmojis(FLAGS) },
];

export const ALL_EMOJIS: readonly Emoji[] = EMOJI_CATEGORIES.flatMap((category) => category.emojis);

/** Sem acento e sem caixa — "coracao" acha "coração". */
export function normalizeSearch(value: string): string {
  return value
    .normalize('NFD')
    .replace(/\p{M}/gu, '')
    .toLowerCase()
    .trim();
}

const INDEX = ALL_EMOJIS.map((emoji) => ({
  emoji,
  haystack: normalizeSearch(`${emoji.label} ${emoji.keywords}`),
}));

/** Todas as palavras digitadas precisam aparecer (no nome ou nas palavras-chave). */
export function searchEmojis(query: string): Emoji[] {
  const terms = normalizeSearch(query).split(/\s+/).filter(Boolean);
  if (terms.length === 0) return [];
  return INDEX.filter(({ haystack }) => terms.every((term) => haystack.includes(term))).map(
    ({ emoji }) => emoji,
  );
}
