/**
 * Catalogo de exames de analises clinicas (dados reais de rotina laboratorial).
 *
 * Invariantes que o teste `tests/seeds/seed-rules.spec.ts` verifica:
 *   - `priceInsurance < pricePrivate` em TODOS os itens (preco de convenio e
 *     sempre tabelado abaixo do particular);
 *   - `code` unico (o schema tem UNIQUE (tenant_id, code));
 *   - toda linha tem categoria, preparo e prazo — as tres colunas aparecem na
 *     tela de catalogo e no modal do orcamento.
 */

export interface SeedExam {
  code: string;
  name: string;
  category: string;
  description: string;
  preparation: string;
  turnaroundHours: number;
  pricePrivate: number;
  priceInsurance: number;
}

const JEJUM_8 = 'Jejum de 8 horas. Manter a medicação de uso contínuo.';
const JEJUM_12 = 'Jejum de 12 horas. Evitar bebida alcoólica nas 72h anteriores.';
const JEJUM_4 = 'Jejum de 4 horas.';
const SEM_PREPARO = 'Não requer preparo. Trazer documento com foto e pedido médico.';
const MANHA = 'Coleta preferencialmente entre 7h e 10h (variação circadiana).';

export const EXAM_CATALOG: readonly SeedExam[] = [
  // ---------------------------------------------------------------- Hematologia
  {
    code: 'HEM001',
    name: 'Hemograma completo',
    category: 'Hematologia',
    description: 'Série vermelha, série branca e contagem de plaquetas.',
    preparation: SEM_PREPARO,
    turnaroundHours: 24,
    pricePrivate: 38.0,
    priceInsurance: 21.5,
  },
  {
    code: 'HEM002',
    name: 'Contagem de reticulócitos',
    category: 'Hematologia',
    description: 'Avaliação da resposta medular na investigação de anemias.',
    preparation: SEM_PREPARO,
    turnaroundHours: 24,
    pricePrivate: 32.0,
    priceInsurance: 18.0,
  },
  {
    code: 'HEM003',
    name: 'VHS - Velocidade de hemossedimentação',
    category: 'Hematologia',
    description: 'Marcador inespecífico de processo inflamatório.',
    preparation: SEM_PREPARO,
    turnaroundHours: 24,
    pricePrivate: 24.0,
    priceInsurance: 13.5,
  },
  {
    code: 'HEM004',
    name: 'Eletroforese de hemoglobina',
    category: 'Hematologia',
    description: 'Triagem de hemoglobinopatias (anemia falciforme, talassemias).',
    preparation: SEM_PREPARO,
    turnaroundHours: 72,
    pricePrivate: 96.0,
    priceInsurance: 54.0,
  },
  {
    code: 'HEM005',
    name: 'Ferritina',
    category: 'Hematologia',
    description: 'Avaliação das reservas corporais de ferro.',
    preparation: JEJUM_4,
    turnaroundHours: 48,
    pricePrivate: 62.0,
    priceInsurance: 34.0,
  },
  {
    code: 'HEM006',
    name: 'Ferro sérico',
    category: 'Hematologia',
    description: 'Dosagem do ferro circulante ligado à transferrina.',
    preparation: JEJUM_8,
    turnaroundHours: 24,
    pricePrivate: 34.0,
    priceInsurance: 19.0,
  },
  {
    code: 'HEM007',
    name: 'Capacidade total de ligação do ferro (TIBC)',
    category: 'Hematologia',
    description: 'Complementa ferro sérico e ferritina no diagnóstico de anemia ferropriva.',
    preparation: JEJUM_8,
    turnaroundHours: 24,
    pricePrivate: 38.0,
    priceInsurance: 21.0,
  },
  {
    code: 'HEM008',
    name: 'Tipagem sanguínea ABO e fator Rh',
    category: 'Hematologia',
    description: 'Determinação do grupo sanguíneo e do fator Rh.',
    preparation: SEM_PREPARO,
    turnaroundHours: 24,
    pricePrivate: 28.0,
    priceInsurance: 15.5,
  },

  // ---------------------------------------------------------------- Coagulação
  {
    code: 'COA001',
    name: 'TAP - Tempo de protrombina com INR',
    category: 'Coagulação',
    description: 'Controle de anticoagulação oral e avaliação da via extrínseca.',
    preparation: SEM_PREPARO,
    turnaroundHours: 24,
    pricePrivate: 34.0,
    priceInsurance: 19.0,
  },
  {
    code: 'COA002',
    name: 'TTPA - Tempo de tromboplastina parcial ativada',
    category: 'Coagulação',
    description: 'Avaliação da via intrínseca da coagulação.',
    preparation: SEM_PREPARO,
    turnaroundHours: 24,
    pricePrivate: 34.0,
    priceInsurance: 19.0,
  },
  {
    code: 'COA003',
    name: 'Fibrinogênio',
    category: 'Coagulação',
    description: 'Dosagem do fator I da coagulação.',
    preparation: SEM_PREPARO,
    turnaroundHours: 24,
    pricePrivate: 42.0,
    priceInsurance: 23.5,
  },
  {
    code: 'COA004',
    name: 'D-dímero',
    category: 'Coagulação',
    description: 'Triagem de eventos tromboembólicos.',
    preparation: SEM_PREPARO,
    turnaroundHours: 24,
    pricePrivate: 88.0,
    priceInsurance: 49.0,
  },

  // ---------------------------------------------------------------- Bioquímica
  {
    code: 'BIO001',
    name: 'Glicose em jejum',
    category: 'Bioquímica',
    description: 'Glicemia de jejum para rastreio e controle de diabetes.',
    preparation: JEJUM_8,
    turnaroundHours: 12,
    pricePrivate: 22.0,
    priceInsurance: 12.5,
  },
  {
    code: 'BIO002',
    name: 'Hemoglobina glicada (HbA1c)',
    category: 'Bioquímica',
    description: 'Média glicêmica dos últimos 90 dias.',
    preparation: SEM_PREPARO,
    turnaroundHours: 24,
    pricePrivate: 52.0,
    priceInsurance: 29.0,
  },
  {
    code: 'BIO003',
    name: 'Curva glicêmica (TOTG 75g)',
    category: 'Bioquímica',
    description: 'Teste oral de tolerância à glicose, coletas em 0 e 120 minutos.',
    preparation: 'Jejum de 8 horas. Permanecer no laboratório durante todo o teste (2 a 3 horas).',
    turnaroundHours: 24,
    pricePrivate: 78.0,
    priceInsurance: 43.0,
  },
  {
    code: 'BIO004',
    name: 'Insulina basal',
    category: 'Bioquímica',
    description: 'Avaliação de resistência insulínica (HOMA-IR).',
    preparation: JEJUM_8,
    turnaroundHours: 48,
    pricePrivate: 68.0,
    priceInsurance: 38.0,
  },
  {
    code: 'BIO005',
    name: 'Colesterol total',
    category: 'Bioquímica',
    description: 'Dosagem do colesterol sérico total.',
    preparation: JEJUM_12,
    turnaroundHours: 12,
    pricePrivate: 24.0,
    priceInsurance: 13.5,
  },
  {
    code: 'BIO006',
    name: 'HDL colesterol',
    category: 'Bioquímica',
    description: 'Fração de alta densidade do colesterol.',
    preparation: JEJUM_12,
    turnaroundHours: 12,
    pricePrivate: 26.0,
    priceInsurance: 14.5,
  },
  {
    code: 'BIO007',
    name: 'LDL colesterol',
    category: 'Bioquímica',
    description: 'Fração de baixa densidade do colesterol.',
    preparation: JEJUM_12,
    turnaroundHours: 12,
    pricePrivate: 26.0,
    priceInsurance: 14.5,
  },
  {
    code: 'BIO008',
    name: 'VLDL colesterol',
    category: 'Bioquímica',
    description: 'Fração de muito baixa densidade do colesterol.',
    preparation: JEJUM_12,
    turnaroundHours: 12,
    pricePrivate: 22.0,
    priceInsurance: 12.0,
  },
  {
    code: 'BIO009',
    name: 'Triglicerídeos',
    category: 'Bioquímica',
    description: 'Dosagem de triglicérides séricos.',
    preparation: JEJUM_12,
    turnaroundHours: 12,
    pricePrivate: 26.0,
    priceInsurance: 14.5,
  },
  {
    code: 'BIO010',
    name: 'Ureia',
    category: 'Bioquímica',
    description: 'Avaliação da função renal.',
    preparation: JEJUM_8,
    turnaroundHours: 12,
    pricePrivate: 20.0,
    priceInsurance: 11.0,
  },
  {
    code: 'BIO011',
    name: 'Creatinina',
    category: 'Bioquímica',
    description: 'Avaliação da função renal com estimativa de TFG.',
    preparation: JEJUM_8,
    turnaroundHours: 12,
    pricePrivate: 20.0,
    priceInsurance: 11.0,
  },
  {
    code: 'BIO012',
    name: 'Ácido úrico',
    category: 'Bioquímica',
    description: 'Investigação de gota e litíase renal.',
    preparation: JEJUM_8,
    turnaroundHours: 12,
    pricePrivate: 22.0,
    priceInsurance: 12.5,
  },
  {
    code: 'BIO013',
    name: 'TGO (AST) - Transaminase oxalacética',
    category: 'Bioquímica',
    description: 'Enzima hepática e muscular.',
    preparation: JEJUM_8,
    turnaroundHours: 12,
    pricePrivate: 22.0,
    priceInsurance: 12.5,
  },
  {
    code: 'BIO014',
    name: 'TGP (ALT) - Transaminase pirúvica',
    category: 'Bioquímica',
    description: 'Enzima predominantemente hepática.',
    preparation: JEJUM_8,
    turnaroundHours: 12,
    pricePrivate: 22.0,
    priceInsurance: 12.5,
  },
  {
    code: 'BIO015',
    name: 'Gama GT (GGT)',
    category: 'Bioquímica',
    description: 'Marcador de colestase e de uso de álcool.',
    preparation: JEJUM_8,
    turnaroundHours: 24,
    pricePrivate: 26.0,
    priceInsurance: 14.5,
  },
  {
    code: 'BIO016',
    name: 'Fosfatase alcalina',
    category: 'Bioquímica',
    description: 'Avaliação hepatobiliar e óssea.',
    preparation: JEJUM_8,
    turnaroundHours: 24,
    pricePrivate: 26.0,
    priceInsurance: 14.5,
  },
  {
    code: 'BIO017',
    name: 'Bilirrubinas total e frações',
    category: 'Bioquímica',
    description: 'Bilirrubina total, direta e indireta.',
    preparation: JEJUM_8,
    turnaroundHours: 24,
    pricePrivate: 30.0,
    priceInsurance: 16.5,
  },
  {
    code: 'BIO018',
    name: 'Proteínas totais e frações',
    category: 'Bioquímica',
    description: 'Proteínas totais, albumina e globulinas.',
    preparation: JEJUM_8,
    turnaroundHours: 24,
    pricePrivate: 30.0,
    priceInsurance: 16.5,
  },
  {
    code: 'BIO019',
    name: 'Albumina',
    category: 'Bioquímica',
    description: 'Avaliação do estado nutricional e da função hepática.',
    preparation: JEJUM_8,
    turnaroundHours: 24,
    pricePrivate: 24.0,
    priceInsurance: 13.0,
  },
  {
    code: 'BIO020',
    name: 'Amilase',
    category: 'Bioquímica',
    description: 'Investigação de pancreatite.',
    preparation: JEJUM_8,
    turnaroundHours: 24,
    pricePrivate: 32.0,
    priceInsurance: 18.0,
  },
  {
    code: 'BIO021',
    name: 'Lipase',
    category: 'Bioquímica',
    description: 'Marcador mais específico de pancreatite aguda.',
    preparation: JEJUM_8,
    turnaroundHours: 24,
    pricePrivate: 36.0,
    priceInsurance: 20.0,
  },
  {
    code: 'BIO022',
    name: 'Sódio sérico',
    category: 'Bioquímica',
    description: 'Avaliação do equilíbrio hidroeletrolítico.',
    preparation: SEM_PREPARO,
    turnaroundHours: 12,
    pricePrivate: 20.0,
    priceInsurance: 11.0,
  },
  {
    code: 'BIO023',
    name: 'Potássio sérico',
    category: 'Bioquímica',
    description: 'Avaliação do equilíbrio hidroeletrolítico.',
    preparation: SEM_PREPARO,
    turnaroundHours: 12,
    pricePrivate: 20.0,
    priceInsurance: 11.0,
  },
  {
    code: 'BIO024',
    name: 'Cálcio total',
    category: 'Bioquímica',
    description: 'Avaliação do metabolismo ósseo e da função paratireoidiana.',
    preparation: JEJUM_8,
    turnaroundHours: 24,
    pricePrivate: 24.0,
    priceInsurance: 13.0,
  },
  {
    code: 'BIO025',
    name: 'Cálcio iônico',
    category: 'Bioquímica',
    description: 'Fração biologicamente ativa do cálcio.',
    preparation: JEJUM_8,
    turnaroundHours: 24,
    pricePrivate: 38.0,
    priceInsurance: 21.0,
  },
  {
    code: 'BIO026',
    name: 'Magnésio',
    category: 'Bioquímica',
    description: 'Dosagem do magnésio sérico.',
    preparation: JEJUM_8,
    turnaroundHours: 24,
    pricePrivate: 28.0,
    priceInsurance: 15.5,
  },
  {
    code: 'BIO027',
    name: 'Fósforo',
    category: 'Bioquímica',
    description: 'Avaliação do metabolismo mineral e ósseo.',
    preparation: JEJUM_8,
    turnaroundHours: 24,
    pricePrivate: 24.0,
    priceInsurance: 13.0,
  },
  {
    code: 'BIO028',
    name: 'CPK - Creatinofosfoquinase total',
    category: 'Bioquímica',
    description: 'Marcador de lesão muscular.',
    preparation: 'Evitar atividade física intensa nas 48 horas anteriores.',
    turnaroundHours: 24,
    pricePrivate: 34.0,
    priceInsurance: 19.0,
  },
  {
    code: 'BIO029',
    name: 'LDH - Desidrogenase láctica',
    category: 'Bioquímica',
    description: 'Marcador inespecífico de lesão tecidual e hemólise.',
    preparation: JEJUM_8,
    turnaroundHours: 24,
    pricePrivate: 30.0,
    priceInsurance: 16.5,
  },

  // ---------------------------------------------------------------- Hormônios
  {
    code: 'HOR001',
    name: 'TSH - Hormônio tireoestimulante',
    category: 'Hormônios',
    description: 'Rastreio e controle de disfunções da tireoide.',
    preparation: MANHA,
    turnaroundHours: 24,
    pricePrivate: 48.0,
    priceInsurance: 27.0,
  },
  {
    code: 'HOR002',
    name: 'T4 livre - Tiroxina livre',
    category: 'Hormônios',
    description: 'Fração livre da tiroxina circulante.',
    preparation: MANHA,
    turnaroundHours: 24,
    pricePrivate: 48.0,
    priceInsurance: 27.0,
  },
  {
    code: 'HOR003',
    name: 'T3 total - Triiodotironina',
    category: 'Hormônios',
    description: 'Complementa a avaliação de hipertireoidismo.',
    preparation: MANHA,
    turnaroundHours: 24,
    pricePrivate: 46.0,
    priceInsurance: 25.5,
  },
  {
    code: 'HOR004',
    name: 'Anti-TPO - Anticorpo antitireoperoxidase',
    category: 'Hormônios',
    description: 'Investigação de tireoidite autoimune (Hashimoto).',
    preparation: SEM_PREPARO,
    turnaroundHours: 48,
    pricePrivate: 78.0,
    priceInsurance: 43.0,
  },
  {
    code: 'HOR005',
    name: 'Cortisol basal',
    category: 'Hormônios',
    description: 'Avaliação da função adrenal.',
    preparation: 'Coleta entre 7h e 9h, em repouso por 30 minutos antes.',
    turnaroundHours: 48,
    pricePrivate: 62.0,
    priceInsurance: 34.0,
  },
  {
    code: 'HOR006',
    name: 'Prolactina',
    category: 'Hormônios',
    description: 'Investigação de galactorreia e irregularidade menstrual.',
    preparation: 'Repouso de 30 minutos antes da coleta. Evitar estímulo mamário nas 24h.',
    turnaroundHours: 48,
    pricePrivate: 56.0,
    priceInsurance: 31.0,
  },
  {
    code: 'HOR007',
    name: 'Testosterona total',
    category: 'Hormônios',
    description: 'Avaliação do eixo gonadal masculino.',
    preparation: MANHA,
    turnaroundHours: 48,
    pricePrivate: 68.0,
    priceInsurance: 38.0,
  },
  {
    code: 'HOR008',
    name: 'Estradiol (E2)',
    category: 'Hormônios',
    description: 'Avaliação do ciclo ovariano e da reserva folicular.',
    preparation: 'Informar a data da última menstruação no momento da coleta.',
    turnaroundHours: 48,
    pricePrivate: 62.0,
    priceInsurance: 34.0,
  },
  {
    code: 'HOR009',
    name: 'FSH - Hormônio folículo-estimulante',
    category: 'Hormônios',
    description: 'Avaliação do eixo hipotálamo-hipófise-gonadal.',
    preparation: 'Informar a data da última menstruação no momento da coleta.',
    turnaroundHours: 48,
    pricePrivate: 56.0,
    priceInsurance: 31.0,
  },
  {
    code: 'HOR010',
    name: 'LH - Hormônio luteinizante',
    category: 'Hormônios',
    description: 'Avaliação da ovulação e do eixo gonadal.',
    preparation: 'Informar a data da última menstruação no momento da coleta.',
    turnaroundHours: 48,
    pricePrivate: 56.0,
    priceInsurance: 31.0,
  },
  {
    code: 'HOR011',
    name: 'Progesterona',
    category: 'Hormônios',
    description: 'Confirmação de ovulação e acompanhamento da fase lútea.',
    preparation: 'Informar a data da última menstruação no momento da coleta.',
    turnaroundHours: 48,
    pricePrivate: 58.0,
    priceInsurance: 32.0,
  },
  {
    code: 'HOR012',
    name: 'Beta-HCG quantitativo',
    category: 'Hormônios',
    description: 'Diagnóstico e acompanhamento de gestação.',
    preparation: SEM_PREPARO,
    turnaroundHours: 12,
    pricePrivate: 58.0,
    priceInsurance: 32.0,
  },
  {
    code: 'HOR013',
    name: 'PTH - Paratormônio intacto',
    category: 'Hormônios',
    description: 'Avaliação do metabolismo do cálcio.',
    preparation: JEJUM_8,
    turnaroundHours: 72,
    pricePrivate: 92.0,
    priceInsurance: 51.0,
  },

  // ---------------------------------------------------------------- Imunologia
  {
    code: 'IMU001',
    name: 'PCR - Proteína C reativa ultrassensível',
    category: 'Imunologia',
    description: 'Marcador de inflamação e de risco cardiovascular.',
    preparation: JEJUM_4,
    turnaroundHours: 24,
    pricePrivate: 42.0,
    priceInsurance: 23.5,
  },
  {
    code: 'IMU002',
    name: 'Fator reumatoide',
    category: 'Imunologia',
    description: 'Triagem de artrite reumatoide.',
    preparation: SEM_PREPARO,
    turnaroundHours: 48,
    pricePrivate: 44.0,
    priceInsurance: 24.5,
  },
  {
    code: 'IMU003',
    name: 'FAN - Fator antinuclear (HEp-2)',
    category: 'Imunologia',
    description: 'Triagem de doenças autoimunes sistêmicas.',
    preparation: SEM_PREPARO,
    turnaroundHours: 72,
    pricePrivate: 86.0,
    priceInsurance: 48.0,
  },
  {
    code: 'IMU004',
    name: 'ASLO - Antiestreptolisina O',
    category: 'Imunologia',
    description: 'Investigação de infecção estreptocócica prévia.',
    preparation: SEM_PREPARO,
    turnaroundHours: 48,
    pricePrivate: 40.0,
    priceInsurance: 22.0,
  },

  // ---------------------------------------------------------------- Sorologia
  {
    code: 'SOR001',
    name: 'HIV 1 e 2 - Teste de 4ª geração',
    category: 'Sorologia',
    description: 'Detecção combinada de antígeno p24 e anticorpos anti-HIV.',
    preparation: SEM_PREPARO,
    turnaroundHours: 48,
    pricePrivate: 72.0,
    priceInsurance: 40.0,
  },
  {
    code: 'SOR002',
    name: 'Hepatite B - HBsAg',
    category: 'Sorologia',
    description: 'Antígeno de superfície do vírus da hepatite B.',
    preparation: SEM_PREPARO,
    turnaroundHours: 48,
    pricePrivate: 64.0,
    priceInsurance: 35.5,
  },
  {
    code: 'SOR003',
    name: 'Hepatite C - Anti-HCV',
    category: 'Sorologia',
    description: 'Anticorpos contra o vírus da hepatite C.',
    preparation: SEM_PREPARO,
    turnaroundHours: 48,
    pricePrivate: 68.0,
    priceInsurance: 38.0,
  },
  {
    code: 'SOR004',
    name: 'VDRL - Sífilis',
    category: 'Sorologia',
    description: 'Triagem não treponêmica de sífilis.',
    preparation: SEM_PREPARO,
    turnaroundHours: 24,
    pricePrivate: 38.0,
    priceInsurance: 21.0,
  },
  {
    code: 'SOR005',
    name: 'Toxoplasmose IgG e IgM',
    category: 'Sorologia',
    description: 'Perfil sorológico para toxoplasmose (rotina pré-natal).',
    preparation: SEM_PREPARO,
    turnaroundHours: 48,
    pricePrivate: 82.0,
    priceInsurance: 45.5,
  },
  {
    code: 'SOR006',
    name: 'Rubéola IgG e IgM',
    category: 'Sorologia',
    description: 'Perfil sorológico para rubéola (rotina pré-natal).',
    preparation: SEM_PREPARO,
    turnaroundHours: 48,
    pricePrivate: 78.0,
    priceInsurance: 43.0,
  },
  {
    code: 'SOR007',
    name: 'Citomegalovírus IgG e IgM',
    category: 'Sorologia',
    description: 'Perfil sorológico para CMV.',
    preparation: SEM_PREPARO,
    turnaroundHours: 48,
    pricePrivate: 84.0,
    priceInsurance: 46.5,
  },
  {
    code: 'SOR008',
    name: 'Dengue NS1',
    category: 'Sorologia',
    description: 'Antígeno NS1 para diagnóstico precoce de dengue.',
    preparation: 'Coletar entre o 1º e o 5º dia de sintomas.',
    turnaroundHours: 24,
    pricePrivate: 88.0,
    priceInsurance: 49.0,
  },

  // ------------------------------------------------------- Marcadores tumorais
  {
    code: 'MAR001',
    name: 'PSA total - Antígeno prostático específico',
    category: 'Marcadores tumorais',
    description: 'Rastreio e acompanhamento de doenças prostáticas.',
    preparation: 'Abstinência sexual de 48 horas. Não realizar após toque retal ou ciclismo.',
    turnaroundHours: 48,
    pricePrivate: 72.0,
    priceInsurance: 40.0,
  },
  {
    code: 'MAR002',
    name: 'PSA livre',
    category: 'Marcadores tumorais',
    description: 'Fração livre do PSA, usada na relação PSA livre/total.',
    preparation: 'Abstinência sexual de 48 horas. Não realizar após toque retal ou ciclismo.',
    turnaroundHours: 48,
    pricePrivate: 76.0,
    priceInsurance: 42.0,
  },
  {
    code: 'MAR003',
    name: 'CA 125',
    category: 'Marcadores tumorais',
    description: 'Marcador de acompanhamento de neoplasia ovariana.',
    preparation: SEM_PREPARO,
    turnaroundHours: 72,
    pricePrivate: 96.0,
    priceInsurance: 53.0,
  },
  {
    code: 'MAR004',
    name: 'CEA - Antígeno carcinoembrionário',
    category: 'Marcadores tumorais',
    description: 'Marcador de acompanhamento de neoplasias do trato digestivo.',
    preparation: SEM_PREPARO,
    turnaroundHours: 72,
    pricePrivate: 88.0,
    priceInsurance: 49.0,
  },

  // ---------------------------------------------------------------- Vitaminas
  {
    code: 'VIT001',
    name: 'Vitamina D - 25-hidroxivitamina D',
    category: 'Vitaminas',
    description: 'Avaliação do status de vitamina D.',
    preparation: SEM_PREPARO,
    turnaroundHours: 48,
    pricePrivate: 98.0,
    priceInsurance: 54.0,
  },
  {
    code: 'VIT002',
    name: 'Vitamina B12 - Cobalamina',
    category: 'Vitaminas',
    description: 'Investigação de anemia megaloblástica e neuropatia.',
    preparation: JEJUM_8,
    turnaroundHours: 48,
    pricePrivate: 74.0,
    priceInsurance: 41.0,
  },
  {
    code: 'VIT003',
    name: 'Ácido fólico',
    category: 'Vitaminas',
    description: 'Dosagem de folato sérico.',
    preparation: JEJUM_8,
    turnaroundHours: 48,
    pricePrivate: 68.0,
    priceInsurance: 38.0,
  },

  // ---------------------------------------------------------------- Uroanálise
  {
    code: 'URI001',
    name: 'EAS - Urina tipo I',
    category: 'Uroanálise',
    description: 'Exame de rotina de urina: físico, químico e sedimentoscopia.',
    preparation: 'Coletar a primeira urina da manhã, jato médio, após higiene íntima.',
    turnaroundHours: 24,
    pricePrivate: 26.0,
    priceInsurance: 14.5,
  },
  {
    code: 'URI002',
    name: 'Urocultura com antibiograma',
    category: 'Uroanálise',
    description: 'Cultura quantitativa de urina com teste de sensibilidade.',
    preparation: 'Jato médio após higiene íntima. Não estar em uso de antibiótico.',
    turnaroundHours: 72,
    pricePrivate: 58.0,
    priceInsurance: 32.0,
  },
  {
    code: 'URI003',
    name: 'Microalbuminúria',
    category: 'Uroanálise',
    description: 'Rastreio de nefropatia diabética.',
    preparation: 'Amostra isolada de urina. Evitar exercício físico intenso nas 24h.',
    turnaroundHours: 48,
    pricePrivate: 48.0,
    priceInsurance: 26.5,
  },
  {
    code: 'URI004',
    name: 'Clearance de creatinina (urina de 24 horas)',
    category: 'Uroanálise',
    description: 'Medida da taxa de filtração glomerular.',
    preparation: 'Coletar toda a urina de 24 horas em frasco fornecido pelo laboratório.',
    turnaroundHours: 48,
    pricePrivate: 56.0,
    priceInsurance: 31.0,
  },

  // ------------------------------------------------------------- Parasitologia
  {
    code: 'PAR001',
    name: 'Parasitológico de fezes (3 amostras)',
    category: 'Parasitologia',
    description: 'Pesquisa de ovos, cistos e larvas em três amostras.',
    preparation: 'Coletar em dias alternados, em frasco com conservante.',
    turnaroundHours: 72,
    pricePrivate: 42.0,
    priceInsurance: 23.0,
  },
  {
    code: 'PAR002',
    name: 'Pesquisa de sangue oculto nas fezes',
    category: 'Parasitologia',
    description: 'Método imunocromatográfico, sem restrição alimentar.',
    preparation: 'Não coletar durante período menstrual ou com sangramento hemorroidário ativo.',
    turnaroundHours: 48,
    pricePrivate: 46.0,
    priceInsurance: 25.5,
  },
  {
    code: 'PAR003',
    name: 'Coprocultura',
    category: 'Parasitologia',
    description: 'Cultura de fezes para bactérias enteropatogênicas.',
    preparation: 'Coletar antes do início de antibiótico, em frasco estéril.',
    turnaroundHours: 96,
    pricePrivate: 62.0,
    priceInsurance: 34.0,
  },

  // ------------------------------------------------------------ Microbiologia
  {
    code: 'MIC001',
    name: 'Cultura de secreção com antibiograma',
    category: 'Microbiologia',
    description: 'Isolamento bacteriano e teste de sensibilidade a antimicrobianos.',
    preparation: 'Coletar antes do início de antibiótico.',
    turnaroundHours: 96,
    pricePrivate: 72.0,
    priceInsurance: 40.0,
  },
  {
    code: 'MIC002',
    name: 'Swab nasal para pesquisa de MRSA',
    category: 'Microbiologia',
    description: 'Rastreio de colonização por Staphylococcus aureus resistente.',
    preparation: 'Não usar pomada nasal nas 24 horas anteriores.',
    turnaroundHours: 72,
    pricePrivate: 66.0,
    priceInsurance: 36.5,
  },
];

/** Subconjunto usado pelo tenant 2 — menor, mas com as mesmas categorias-chave. */
export const EXAM_CATALOG_SECONDARY: readonly SeedExam[] = EXAM_CATALOG.filter((exam) =>
  [
    'HEM001',
    'HEM003',
    'HEM005',
    'COA001',
    'COA002',
    'BIO001',
    'BIO002',
    'BIO005',
    'BIO009',
    'BIO010',
    'BIO011',
    'BIO012',
    'BIO013',
    'BIO014',
    'HOR001',
    'HOR002',
    'HOR012',
    'IMU001',
    'VIT001',
    'VIT002',
    'URI001',
    'URI002',
    'PAR001',
    'MAR001',
  ].includes(exam.code),
);
